### PR TITLE
Fixes React 15.5 Warnings

### PR DESCRIPTION
**Pull request by wilbert-abreu**

### CODE REVIEW

**Comment by wilbert-abreu** [comment]
@loktar00 Please merge this in asap as it's causing warnings on my end. Thanks!

**Comment by wilbert-abreu** [comment]
@loktar00 any updates on this? This is the last one of my packages that is causing a warning. Thanks!

**Comment by loktar00** [comment]
nice thanks! Merged will get it on npm by the end of the day!

**Comment by wilbert-abreu** [comment]
@loktar00  Thanks!

**Pull request merged**
