### PR TITLE
Migrate to es6 + refactor

### PR DESCRIPTION
**Pull request by sergeylaptev**

### CODE REVIEW

**Comment by loktar00** [comment]
Why was this closed? Was going to go through it this weekend and before merging it in since it was such a big change.

**Comment by sergeylaptev** [comment]
First of all it has merging conflict (need to make rebase), and I thought if I don't have feedback several days this PR not needed to anyone:)

**Comment by loktar00** [comment]
Thanks a lot for all the hard work on this!

**Comment by sergeylaptev** [comment]
You are welcome. I'll be glad to help with this small project as far as possible.

**Pull request merged**
