### PR TITLE
Added Jest tests, requestAnimationFrame, and aggregated scroll handlers

### PR DESCRIPTION
**Pull request by rivertam**
Wanted to learn Jest, so I made some tests for this repo. Hope you don't mind it/actually want tests. We're planning on using this at http://aplus.com, but I wanted to make sure it had some reasonable tests before relying on it. Definitely more possible tests, but this should be sufficient for the PRs I plan to make regarding #54 and #55.

### CODE REVIEW

**Comment by rivertam** [comment]
I broke your CI. T_T I'm sorry.

Why is your CI linting node_modules?

**Comment by rivertam** [comment]
I'm repurposing this pull request to include #54 and #55.

The bulk of this work is in leveraging a library I created called `manage-scroll-handlers` ([repo here](https://github.com/rivertam/manage-scroll-handlers)]

**Comment by sergeylaptev** [comment]
I appreciate your work. Unfortunately I can play with it only on the weekend. Btw I personally don't like jest. My personal choice is mocha + enzyme + expect. It will be great If you are ready to implement tests with this stack;)

**Comment by rivertam** [comment]
I'm down to take a look. We use mocha at work, and it's certainly simpler. I chose Jest partly because it does automatic mocking, which works out great for mocking `inViewport` and `parentScroll`. I appreciate the time, even if you decide to just scrap the tests entirely. I would ask that you take a look at the package I created. I tried to make it as minimal (and small) as possible, and it almost certainly has multiple flaws.

**Comment by sergeylaptev** [comment]
For mocking good tools are:
https://www.npmjs.com/package/rewire
https://www.npmjs.com/package/mockery

Jest brings too much magic with it:)
I'll check your library too. Can you export your module as module.exports? require(...).default looks horrible

**Comment by rivertam** [comment]
@sergeylaptev What do you think about this solution? (using `import` instead of `require`)

Personally, I think it's prettier in general, and now manage-scroll-handlers actually exports correctly.

**Pull request closed without merging**
